Name:Harshith Nagaraj

Reg no:251100610023

Branch:CSE

Date: 11th Aug 2025 Tuesday

1. WAP to search for a number 9 present in the list [89, 14, 21, 34, 55, 9]

In [ ]:
# Program to search for number 9 in the list

# Given list
numbers = [89, 14, 21, 34, 55, 3, 9]#9 is added later on , not present in the question

# Number to search
target = 9

# Check if target is present
if target in numbers:
    print(f"{target} is present in the list.")
else:
    print(f"{target} is not present in the list.")


9 is present in the list.


2. Find biggest and smallest from the list

In [ ]:
# Find biggest and smallest
numbers = [89, 14, 21, 34, 55, 3]
print("Biggest number:", max(numbers))
print("Smallest number:", min(numbers))


Biggest number: 89
Smallest number: 3


3. Filter numbers greater than 50

In [ ]:
# Filter numbers greater than 50
numbers = [89, 14, 21, 34, 55, 3]
greater_than_50 = [num for num in numbers if num > 50]
print("Numbers greater than 50:", greater_than_50)


Numbers greater than 50: [89, 55]


4. Count number of elements in the list

In [ ]:
# Count number of elements
numbers = [89, 14, 21, 34, 55, 3]
print("Number of elements:", len(numbers))


Number of elements: 6


5. Find sum and average

In [ ]:
# Sum and average
numbers = [89, 14, 21, 34, 55, 3]
total = sum(numbers)
average = total / len(numbers)
print("Sum:", total)
print("Average:", average)


Sum: 216
Average: 36.0


6. WAP to get input from the use and get the gross pay

In [ ]:
# Gross pay calculation
hours = float(input("Enter Hours: "))
rate = float(input("Enter Rate: "))
pay = hours * rate
print("Pay:", pay)


Enter Hours: 35
Enter Rate: 2.75
Pay: 96.25


7. Gross pay with overtime (computepay function)

In [ ]:
# Gross pay with overtime
def computepay(hours, rate):
    if hours > 40:
        overtime_hours = hours - 40
        return (40 * rate) + (overtime_hours * rate * 1.5)
    else:
        return hours * rate

hours = float(input("Enter Hours: "))
rate = float(input("Enter Rate: "))
pay = computepay(hours, rate)
print("Pay:", pay)


Enter Hours: 45
Enter Rate: 2.75
Pay: 130.625


This code block uses sorted() , not asked by sir.

In [ ]:
# Normal Sort using Python's built-in sorted()
numbers = [89, 14, 21, 34, 55, 3]

sorted_list = sorted(numbers)

print("Original List:", numbers)
print("Normal Sort:", sorted_list)


Original List: [89, 14, 21, 34, 55, 3]
Normal Sort: [3, 14, 21, 34, 55, 89]


8. Bubble sort

In [ ]:
# Bubble Sort
numbers = [89, 14, 21, 34, 55, 3]

def bubble_sort(arr):
    arr = arr.copy()
    n = len(arr)
    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr

print("Original List:", numbers)
print("Bubble Sort:", bubble_sort(numbers))


Original List: [89, 14, 21, 34, 55, 3]
Bubble Sort: [3, 14, 21, 34, 55, 89]


9. Insertion Sort

In [ ]:
# Insertion Sort
numbers = [89, 14, 21, 34, 55, 3]

def insertion_sort(arr):
    arr = arr.copy()
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
    return arr

print("Original List:", numbers)
print("Insertion Sort:", insertion_sort(numbers))


Original List: [89, 14, 21, 34, 55, 3]
Insertion Sort: [3, 14, 21, 34, 55, 89]


10. Quick Sort

In [ ]:
# Quick Sort
numbers = [89, 14, 21, 34, 55, 3]

def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort(left) + middle + quick_sort(right)

print("Original List:", numbers)
print("Quick Sort:", quick_sort(numbers))


Original List: [89, 14, 21, 34, 55, 3]
Quick Sort: [3, 14, 21, 34, 55, 89]


Sorting combined using functions

In [ ]:
# List to sort
numbers = [89, 14, 21, 34, 55, 3]

def bubble_sort(arr):
    arr = arr.copy()
    n = len(arr)
    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr

def insertion_sort(arr):
    arr = arr.copy()
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
    return arr

def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort(left) + middle + quick_sort(right)

def normal_sort(arr):
    return sorted(arr)

print("Original List:", numbers)
print("Bubble Sort:  ", bubble_sort(numbers))
print("Insertion Sort:", insertion_sort(numbers))
print("Quick Sort:   ", quick_sort(numbers))
print("Normal Sort:  ", normal_sort(numbers))


Original List: [89, 14, 21, 34, 55, 3]
Bubble Sort:   [3, 14, 21, 34, 55, 89]
Insertion Sort: [3, 14, 21, 34, 55, 89]
Quick Sort:    [3, 14, 21, 34, 55, 89]
Normal Sort:   [3, 14, 21, 34, 55, 89]


19th August 2025

Tuesday

In [ ]:
import scipy
print('Scipy:%s' % scipy.__version__)
import numpy
print("NumPy:", numpy.__version__)
import sklearn
print("scikit-learn:", sklearn.__version__)


Scipy:1.16.1
NumPy: 2.0.2
scikit-learn: 1.6.1


using functions in python

In [ ]:
def add_numbers(x,y):
  return x+y

In [ ]:
a=15;b=1;
add_numbers(a,b)

16

In [ ]:
def add_numbers(x,y,z=None):
  if (z==None):
    return x+y
  else:
    return x+y+z

In [ ]:
print(add_numbers(30,3))

33


In [ ]:
print(add_numbers(10,20,30))

60


In [ ]:
def add_numbers(x,y,z=None,flag=False):
  if(flag):
    print('Flag is on!')
  if(z==None):
    return x+y
  else:
    return x+y+z

In [ ]:
print(add_numbers(10,20,25,flag=True))

Flag is on!
55


In [ ]:
#assign function to a variable
a=add_numbers
a(16,12)

28

In [ ]:
type('h')

str

In [ ]:
type(None)

NoneType

In [ ]:
type(0)

int

In [ ]:
type("hello")

str

In [ ]:
type(1.2123)

float

In [ ]:
type(add_numbers)

function

In [ ]:
x=(1,'a',2,'b',1.2)
type(x)

tuple

In [ ]:
# x.append(3.3)
# print(x)
# #it wont append

In [ ]:
x=[1,'a',2,'b']
type(x)

list

In [ ]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


In [ ]:
#loop through items in a list

for item in x:
  print(item)

1
a
2
b
3.3


In [ ]:
#lenght of the list
len(x)

5

list is mutable while tuple is not

In [ ]:
i=0
while(i!=len(x)):
  print(x[i])
  i=i+1

1
a
2
b
3.3


In [ ]:
#Concatenating the 2 list
[1,2]+[3,4]

[1, 2, 3, 4]

In [ ]:
(1,2)+(3,4)

(1, 2, 3, 4)

In [ ]:
#repeat the elements
[10,1,3.3]*3

[10, 1, 3.3, 10, 1, 3.3, 10, 1, 3.3]

In [ ]:
#check if the number is present in the list or not
3 in [1,2,3,4,5]

True

In [ ]:
x='This is a string'

In [ ]:
print(x[0])
#first character

T


In [ ]:
print(x[0:1])
#first character method 2

T


In [ ]:
#this will start from 0 and stops before 6 , it also includes the blank space
print(x[0:6])

This i


In [ ]:
#returns the slice starting from the 4th element from the end and stopping before 2
print(x[-4:-2])

ri


In [ ]:
x[-8:-3]

'a str'

In [ ]:
#starts from 0 to before 3
x[:3]

'Thi'

In [ ]:
x[3:]

's is a string'

above are the character slicing, word slicing will come later

In [ ]:
firstname='MSIS'
lastname='Manipal'

In [ ]:
print(firstname+' '+lastname)

MSIS Manipal


In [ ]:
print(firstname*3)

MSISMSISMSIS


In [ ]:
print('is' in firstname)

False


In [ ]:
print('IS'in firstname)

True


In [ ]:
#slicing the sentence

firstname='Tom Mitchell Machine Learning Scientist'.split(' ')[0]

middlename='Tom Mitchell Machine Learning Scientist'.split(' ')[1]

lastname='Tom Mitchell Machine Learning Scientist'.split(' ')[-1]

In [ ]:
print(firstname)

Tom


In [ ]:
print(middlename)

Mitchell


In [ ]:
print(lastname)

Scientist


In [ ]:
print(firstname+' '+middlename+' '+lastname)

Tom Mitchell Scientist


In [ ]:
#have to convert objects to strings before concatination else it will throw error saying cannot add integer to a string
#single quote or double quote means its a string
'Chrish'+'2'

'Chrish2'

In [ ]:
'Chris'+str(2)

'Chris2'

In [ ]:
#Dictionary
x={'Tom':'tom.m@gmail.com','Bill Gates':'billgates@microsoft.com'}

In [ ]:
x['Bill Gates']

'billgates@microsoft.com'

In [ ]:
x.update({'harshith': 'harshith462003@gmail.com', 'Adhitya': 'aditykr142@gmail.com'})


In [ ]:
x['harshith']

'harshith462003@gmail.com'

In [ ]:
x['Adhitya']

'aditykr142@gmail.com'

In [ ]:
x

{'Tom': 'tom.m@gmail.com',
 'Bill Gates': 'billgates@microsoft.com',
 'harshith': 'harshith462003@gmail.com',
 'Adhitya': 'aditykr142@gmail.com'}

In [ ]:
for name in x:
  print(name)

Tom
Bill Gates
harshith
Adhitya


In [ ]:
for name in x:
  print(x[name])

tom.m@gmail.com
billgates@microsoft.com
harshith462003@gmail.com
aditykr142@gmail.com


In [ ]:
x=('Tom','Mitchell','tom.m@gmail.com')
fname,lname,email=x
lname

'Mitchell'

In [ ]:
lname

'Mitchell'

In [ ]:
fname

'Tom'

In [ ]:
x=('Tom','Mitchell','tom.m@gmail.com','MSIS')
fname,lname,email,dept=x
dept

'MSIS'

In [ ]:
sales_record={
    'price':3.24,
    'num_items':4,
    'person':'tom',
    'email':'tom.m@gmail.com'
}

In [ ]:
sale_statement='{} bought {} items at a price of INR each for a total of INR {}'.format(sales_record['person'],sales_record['num_items'],sales_record['price']*sales_record['num_items'])

In [ ]:
print (sale_statement)

tom bought 4 items at a price of INR each for a total of INR 12.96


In [ ]:
import datetime as dt
import time as tm

In [ ]:
#time in seconds from 1st jan 1970
tm.time()

1755596112.3581824

In [ ]:
from datetime import date
from datetime import time
from datetime import datetime

In [ ]:
today=date.today()
print('today is ',today)


today is  2025-08-19


In [ ]:
dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2025, 8, 19, 9, 40, 21, 675832)

In [ ]:
today=dt.date.today()
delta=dt.timedelta(days=100)


In [ ]:
today-delta

datetime.date(2025, 5, 11)

In [ ]:
today>today-delta

True

### ASSIGNMENT 2 :19th August 2025 Tuesday

1. Implementation of the classic quicksort algorithm in Python.

In [ ]:
#1. Implementation of the classic quicksort algorithm in Python.
numbers = [89, 14, 21, 34, 55, 3]

def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort(left) + middle + quick_sort(right)

print("Original List:", numbers)
print("Quick Sort:", quick_sort(numbers))


Original List: [89, 14, 21, 34, 55, 3]
Quick Sort: [3, 14, 21, 34, 55, 89]


2. write the output of the following code:

a.

In [ ]:
hello = 'hello'
world = "world"
print(hello)
print(len(hello))
hw = hello + ' ' + world
print(hw)
hw12 = '%s %s %d' % (hello, world, 12)
print(hw12)

hello
5
hello world
hello world 12


b.

In [ ]:
s = "hello"
print(s.capitalize())
print(s.upper())
print(s.rjust(7))
print(s.center(7))
print(s.replace('l', '(ell)'))
print('  world '.strip())

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world



3. rewrite the following code using list comprehension technique.

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


In [ ]:
nums=[0,1,2,3,4]
squares=[x**2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


4. Consider the following dictionary

d = {'person': 2, 'cat': 4, 'spider': 8}

write a code to iterate over the keys to print "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}

for key, value in d.items():
    print(f"A {key} has {value} legs")


A person has 2 legs
A cat has 4 legs
A spider has 8 legs


5. use the items method to rewrite the above code to access the keys and their corresponding values.

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}

for key, value in d.items():   # .items() gives (key, value) pairs
    print(f"A {key} has {value} legs")


A person has 2 legs
A cat has 4 legs
A spider has 8 legs


6. Write the output of the following lines

In [ ]:
nums = list(range(5))
print(nums)
print(nums[2:4])
print(nums[2:])
print(nums[:2])
print(nums[:])
print(nums[:-1])
nums[2:4] = [8, 9]
print(nums)

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


7. Write the differences between the following two code block

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    	  print(animal)


animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
   	    print('#%d: %s' % (idx + 1, animal))

cat
dog
monkey
#1: cat
#2: dog
#3: monkey


8. Consider the following code

	nums = [0, 1, 2, 3, 4]
	squares = []
	for x in nums:
    
    squares.append(x ** 2)
    
	print(squares)

    rewrite the above code using a list comprehension technique

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


In [ ]:
nums=[1,2,3,4]
squares=[x**2 for x in nums]
print(squares)

[1, 4, 9, 16]


Q9. Print square of even numbers from list

In [ ]:
nums = [0, 1, 2, 3, 4]

for n in nums:
    if n % 2 == 0:   # check even
        print(n**2)


0
4
16


Q10. Using dictionary

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}

for key in d:
    print(f"A {key} has {d[key]} legs")


A person has 2 legs
A cat has 4 legs
A spider has 8 legs


Q11. Using .items()

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}

for key, value in d.items():
    print(f"A {key} has {value} legs")


A person has 2 legs
A cat has 4 legs
A spider has 8 legs


Q12. Numpy array operations //not done in class

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a))            # <class 'numpy.ndarray'>
print(a.shape)            # (3,)
print(a[0], a[1], a[2])   # 1 2 3
a[0] = 5
print(a)                  # [5 2 3]

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)            # (2, 3)
print(b[0, 0], b[0, 1], b[1, 0])  # 1 2 4


<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Q13. Array creation

In [ ]:
import numpy as np

a = np.zeros((2,2))
print(a)
# [[0. 0.]
#  [0. 0.]]

b = np.ones((1,2))
print(b)
# [[1. 1.]]

c = np.full((2,2), 7)
print(c)
# [[7 7]
#  [7 7]]

d = np.eye(2)
print(d)
# [[1. 0.]
#  [0. 1.]]

e = np.random.random((2,2))
print(e)   # random 2x2 values between 0 and 1

Q14. Rank 2 array & slicing

In [ ]:
import numpy as np

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9,10,11,12]])

b = a[0:2, 1:3]   # rows 0,1 and cols 1,2
print(b)


[[2 3]
 [6 7]]


Q15. Elements bigger than 2

In [ ]:
a1 = np.array([[1,2], [3,4], [5,6]])

res = a1[a1 > 2]
print(res)


[3 4 5 6]


Q16. Dot products

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))          # 219
print(np.dot(v, w))      # 219

print(x.dot(v))          # [29 67]
print(np.dot(x, v))      # [29 67]

print(x.dot(y))          # [[19 22]
                         #  [43 50]]
print(np.dot(x, y))      # same


219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Q17. Sums


In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])

# (a) sum of all elements
print(np.sum(x))         # 10

# (b) sum of each column
print(np.sum(x, axis=0)) # [4 6]

# (c) sum of each row
print(np.sum(x, axis=1)) # [3 7]

10
[4 6]
[3 7]
